# Generated by Django 4.2.2 on 2023-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="logo",
            field=models.CharField(max_length=200),
        ),
    ]
