# Generated by Django 4.2.2 on 2023-08-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vending", "0003_alter_product_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
